version: '3'


services:
  backend:
    build:
      context: ./example-backend
    ports:
      - "8080:8080"
    command: ./server

  frontend:
    build:
      context: ./example-frontend
    ports:
      - "5000:5000"
